name: reveil
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - notebook
  - pip:
      - accelerate==1.6.0
      - bitsandbytes==0.45.5
      - datasets==3.6.0
      - evaluate==0.4.3
      - lightning==2.5.1.post0
      - pandas==2.2.3
      - numpy==1.26.4
      - scikit-image==0.25.2
      - scipy==1.15.3
      - pillow==11.2.1
      - torch==2.7.0
      - torchvision==0.22.0
      - torchmetrics==1.7.1
      - transformers==4.51.3
      - tokenizers==0.21.1
      - safetensors==0.5.3
      - peft==0.15.2
      - pytorch-lightning==2.5.1.post0
      - qwen-vl-utils==0.0.11
      - roboflow==1.1.63
      - opencv-python==4.11.0.86
      - rich==14.0.0
      - tqdm==4.67.1
      - maestro==1.1.0rc2