---
title: "Data inspection & visualization for Re-Veil data"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=TRUE, results='hide', warning=FALSE, message=FALSE, eval=TRUE}
shhh <- suppressPackageStartupMessages

shhh(library(dplyr))
shhh(library(ggplot2))
shhh(library(ggrepel))
shhh(library(forcats))
shhh(library(ggcorrplot))
shhh(library(cowplot))
shhh(library(lme4))
shhh(library(lmerTest))
shhh(library(tidyr))
shhh(library(stringr))
shhh(library(HDInterval))
shhh(library(MASS))
shhh(library(brms))
shhh(library(boot))
shhh(library(purrr))
shhh(library(mgcv))
shhh(library(rsample))
shhh(library(gridExtra))
shhh(library(cmdstanr))
```


# Read in MoTR Data
```{r ZH-Data, echo=TRUE, warning=FALSE, eval=TRUE}
# The path to the zh data
zh_path <- "../data/Human/zh/rm-zh-chr"
zh_names <- list.files(zh_path)

# Read in the data from each participant and add to the data frame
zh_df <- data.frame()
for(name in zh_names){
  subj <- gsub("reader_", "", gsub("_reading_measures.csv", "", name))
  temp_df <- read.csv(paste0(zh_path, "/", name)) %>%
    mutate(subj_id = paste0("s", subj),
           stim_id = paste0("t", stim_id)) %>%
    rename(word_id = exp_word_id,
           subj = subj_id,
           easiness = difficulty)
  zh_df <- rbind(zh_df, temp_df)
} 

# View(zh_df)
```

```{r EN-Data, echo=TRUE, warning=FALSE, eval=TRUE}
# The path to the en data
en_path <- "../data/Human/en/rm_may"
en_names <- list.files(en_path)

# Read in the data from each participant and add to the data frame
en_df <- data.frame()
for(name in en_names){
  subj <- gsub("reader_", "", gsub("_reading_measures.csv", "", name))
  temp_df <- read.csv(paste0(en_path, "/", name)) %>%
    mutate(subj_id = paste0("s", subj),
           stim_id = paste0("t", stim_id)) %>%
    rename(word_id = exp_word_id,
           subj = subj_id,
           easiness = difficulty)
  en_df <- rbind(en_df, temp_df)
} 

# View(en_df)
```

# Prepare the reading time data for modeling
```{r ZH-RT-Data, echo=TRUE, warning=FALSE, eval=TRUE}
zh_rt <- zh_df %>%
  # rename(word_len = token_len) %>%
  dplyr::select(expr_id, subj, stim_id, item_id, trial_id, word_id, word_len, zipf_freq, surp, renyi, rev, easiness, first_duration, total_duration, gaze_duration, go_past_time, FPFix, FPReg, RegIn_incl, NFix) %>%
  mutate(
    across(
      c(first_duration, total_duration, gaze_duration, go_past_time, FPFix, FPReg, RegIn_incl, NFix),
      ~ if_else(total_duration == 0, NA_real_, .)
    )
  ) %>%
  mutate(skip = if_else(FPFix == 1, 0, 1),
         easiness = if_else(easiness == "top", "Upper", "Lower")) %>%
  mutate(msurp = surp / word_len,
         mrenyi = renyi / word_len,
         word_len_px = word_len * 18
         ) %>%
  dplyr::select(-surp, -renyi) %>%
  mutate(
    rev = factor(rev, levels = c("f", "u", "l"), labels = c("Full", "Upper", "Lower")),
    easiness = factor(easiness, levels = c("Upper", "Lower")),
    expr_id = factor(expr_id, levels = c("zh1", "en1"), labels = c("ZH", "EN")),
    subj_id = as.numeric(factor(subj, levels = unique(subj)))
    ) %>%
  mutate(len = word_len, 
         freq = zipf_freq,
         surp = msurp,
         renyi = mrenyi,
         word_len = scale(word_len, center = TRUE, scale = TRUE)[, 1],
         len_px = scale(word_len_px,center = TRUE, scale = TRUE)[, 1],
         zipf_freq = scale(zipf_freq, center = TRUE, scale = TRUE)[, 1],
         msurp = scale(msurp, center = TRUE, scale = TRUE)[, 1],
         mrenyi = scale(mrenyi, center = TRUE, scale = TRUE)[, 1]
         ) %>%
  group_by(subj, item_id) %>%
  arrange(subj, item_id, word_id) %>%
  mutate(prev_surp = lag(surp),
        prev_renyi = lag(renyi),
        prev_freq = lag(freq),
        prev_len = lag(len)) %>%
  ungroup() %>%
  filter(!is.na(total_duration)) %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0, renyi > 0, prev_renyi > 0)
  
# View(zh_rt)

# write.csv(zh_rt, "./data/zh/zh_rt.csv")
```

```{r EN-RT-Data, echo=TRUE, warning=FALSE, eval=TRUE}
en_rt <- en_df %>%
  dplyr::select(expr_id, subj, stim_id, item_id, trial_id, word_id, word_len, word_len_px, zipf_freq, msurp, mrenyi, rev, easiness, first_duration, total_duration, gaze_duration, go_past_time, FPFix, FPReg, RegIn_incl, NFix) %>%
  mutate(
    across(
      c(first_duration, total_duration, gaze_duration, go_past_time, FPFix, FPReg, RegIn_incl, NFix),
      ~ if_else(total_duration == 0, NA_real_, .)
    )
  ) %>%
  mutate(skip = if_else(FPFix == 1, 0, 1),
         easiness = if_else(easiness == "top", "Upper", "Lower")) %>%
  mutate(
    rev = factor(rev, levels = c("f", "u", "l"), labels = c("Full", "Upper", "Lower")),
    easiness = factor(easiness, levels = c("Upper", "Lower")),
    expr_id = factor(expr_id, levels = c("zh1", "en1"), labels = c("ZH", "EN")),
    subj_id = as.numeric(factor(subj, levels = unique(subj)))
    ) %>%
  mutate(len = word_len, 
         freq = zipf_freq,
         surp = msurp,
         renyi = mrenyi,
         word_len = scale(word_len, center = TRUE, scale = TRUE)[, 1],
         len_px = scale(word_len_px,center = TRUE, scale = TRUE)[, 1],
         zipf_freq = scale(zipf_freq, center = TRUE, scale = TRUE)[, 1],
         msurp = scale(msurp, center = TRUE, scale = TRUE)[, 1],
         mrenyi = scale(mrenyi, center = TRUE, scale = TRUE)[, 1]
         ) %>%
  group_by(subj, item_id) %>%
  arrange(subj, item_id, word_id) %>%
  mutate(prev_surp = lag(surp),
        prev_renyi = lag(renyi),
        prev_freq = lag(freq),
        prev_len = lag(len)) %>%
  ungroup() %>%
  filter(!is.na(total_duration)) %>%
  filter(freq > 0, prev_freq > 0, surp > 0, prev_surp > 0, renyi > 0, prev_renyi > 0)

# View(en_rt)

# write.csv(en_rt, "./data/en/en_rt.csv")
```

```{r ZH-EN-combined, echo=TRUE, warning=FALSE, eval=TRUE}
zhen_rt <- rbind(zh_rt, en_rt) 

zhen_rt <- zhen_rt %>%
  mutate(msubj_id = as.numeric(factor(subj, levels = unique(subj)))
         )
  

# View(zhen_rt)
# write.csv(zhen_rt, "./data/zhen_rt.csv")
```

# Prepare the RCQ and self rating data
```{r RCQ-ZH, echo=TRUE, warning=FALSE, eval=TRUE}
zh_rcq <- zh_df %>%
  dplyr::select(expr_id, subj, stim_id, item_id, question_id, trial_id, correctness, rev, easiness) %>%
  filter(question_id != -99) %>%
  filter(!stim_id %in% c("t4")) %>%  # only one intial participant read stimulus 4
  distinct() %>%
  mutate(rev = factor(rev, levels = c("f", "u", "l"), labels = c("Full", "Upper", "Lower")),
         easiness = factor(easiness, levels = c("equal", "top", "bottom"), labels = c("Equal", "Upper", "Lower")),
         subj_id = as.numeric(factor(subj, levels = unique(subj)))
         )
zh_rcq

en_rcq <- en_df %>%
  dplyr::select(expr_id, subj, stim_id, item_id, question_id, trial_id, correctness, rev, easiness) %>%
  filter(question_id != -99) %>%
  distinct() %>%
  mutate(rev = factor(rev, levels = c("f", "u", "l"), labels = c("Full", "Upper", "Lower")),
         easiness = factor(easiness, levels = c("equal", "top", "bottom"), labels = c("Equal", "Upper", "Lower")),
         subj_id = as.numeric(factor(subj, levels = unique(subj)))
         )

zhen_rcq <- rbind(zh_rcq, en_rcq) 
zhen_rcq <- zhen_rcq %>%
  mutate(msubj_id = as.numeric(factor(subj, levels = unique(subj))),
        expr_id = factor(expr_id, levels = c("zh1", "en1"), labels = c("ZH", "EN")))

rcqsum <- zhen_rcq %>%
  group_by(expr_id, rev) %>%
  summarise(
    mean_correctness = mean(correctness, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  ) %>%
  mutate(
    label = paste0(round(mean_correctness * 100), "%")
  )

rcqsum

subjrcq <- zhen_rcq %>%
  group_by(expr_id, stim_id, question_id, rev) %>%
  summarise(mean_correctness = mean(correctness, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(names_from = rev, values_from = mean_correctness) %>%
  drop_na()

subjrcq

zh_subjrcq <- subjrcq %>%
  filter(expr_id == "ZH")
en_subjrcq <- subjrcq %>%
  filter(expr_id == "EN")

zht_Whole_Upper <- t.test(zh_subjrcq$Full, zh_subjrcq$Upper, paired = TRUE)
ent_Whole_Upper <- t.test(en_subjrcq$Full, en_subjrcq$Upper, paired = TRUE)
zht_Whole_Lower <- t.test(zh_subjrcq$Full, zh_subjrcq$Lower, paired = TRUE)
ent_Whole_Lower <- t.test(en_subjrcq$Full, en_subjrcq$Lower, paired = TRUE)
zht_Upper_Lower <- t.test(zh_subjrcq$Upper, zh_subjrcq$Lower, paired = TRUE)
ent_Upper_Lower <- t.test(en_subjrcq$Upper, en_subjrcq$Lower, paired = TRUE)

list(
  zh_Whole_vs_Upper = zht_Whole_Upper,
  en_Whole_vs_Upper = ent_Whole_Upper,
  zh_Whole_vs_Lower = zht_Whole_Lower,
  en_Whole_vs_Lower = ent_Whole_Lower,
  zh_Upper_vs_Lower = zht_Upper_Lower,
  en_Upper_vs_Lower = ent_Upper_Lower
)
```

```{r Readability Rating data prep, echo=TRUE, warning=FALSE, eval=TRUE}
easysum <- zhen_rcq %>%
  dplyr::select(expr_id, subj, easiness) %>%
  distinct() %>%
  mutate(easiness = factor(easiness, levels = c("Equal", "Upper", "Lower")),
         expr_id = factor(expr_id, levels = c("ZH", "EN"), labels=c("ZH", "EN"))) %>%
  count(expr_id, easiness) %>%
  group_by(expr_id) %>%
  mutate(
    easiness_prop = n / sum(n),
    label = paste0(round(easiness_prop * 100), "%"),
    ypos = case_when(
      easiness == "Upper" ~ 0.50,
      easiness == "Equal" ~ if_else(expr_id == "EN", 0.96, 0.94),
      easiness == "Lower" ~ if_else(expr_id == "EN", 0.02, 0.08),
      TRUE ~ NA_real_
    )
  )
easysum

label_easysum <- easysum %>%
  group_by(expr_id) %>%
  summarise(n = sum(n), .groups = "drop") %>%
  mutate(
    center_label = paste0(expr_id, "\n (n=", n, ")"),
    x = 0.5,
    y = 0.25
  )

```

```{r Readability Donut plot, echo=TRUE, warning=FALSE, eval=TRUE}
ggplot(easysum, aes(x = 2, y = easiness_prop, fill = easiness)) +
  geom_col(width = 1, color = "white") +
  coord_polar(theta = "y") +
  geom_text(aes(y = ypos, label = label), color = "black", size = 4) +
  geom_text(
    data = label_easysum,
    aes(x = x, y = y, label = center_label),
    inherit.aes = FALSE,
    size = 5,
    fontface = "bold"
  ) +
  xlim(0.5, 2.5) +
  facet_wrap(~ expr_id) +
  # facet_grid(expr_id ~ .) +   # vertical alignment
  scale_fill_brewer(palette = "Set2") +
  theme_void() +
  labs(
    # title = "Perceived Readability: Upper vs. Lower Word Parts",
    fill = "Readability"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
    strip.text = element_blank(),
    panel.spacing = unit(0.1, "lines")
  )

# ggsave("./visualization/readability_comparison_donut.pdf", width = 4, height = 8)

```


```{r}
ggplot(easysum, aes(x = 2, y = easiness_prop, fill = easiness)) +
  geom_col(width = 1, color = "white") +
  coord_polar(theta = "y") +
  geom_text(aes(y = ypos, label = label), color = "black", size = 4) +
  geom_text(
    data = label_easysum,
    aes(x = x, y = y, label = center_label),
    inherit.aes = FALSE,
    size = 5,
    fontface = "bold"
  ) +
  xlim(0.5, 2.5) +
  facet_wrap(~ expr_id) +
  scale_fill_manual(
    values = c(
      "Upper" = "#FC8D62",   # orange
      "Lower" = "#8DA0CB",   # blue
      "Equal" = "#B3B3B3"    # neutral gray
    ),
    labels = c(
      "Upper" = "Upper easier than Lower",
      "Lower" = "Lower easier than Upper",
      "Equal" = "Upper & Lower equally easy"
    )
  ) +
  theme_void() +
  labs(
    fill = "Self-rated ease of reading"
  ) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 12, face = "bold"),
    strip.text = element_blank(),
    panel.spacing = unit(0.1, "lines")
  )

# ggsave("./visualization/readability_comparison_donut_pretty.pdf", width = 7, height = 4)
```



```{r RT by-subj Comparison, echo=TRUE, warning=FALSE, eval=TRUE}
subj_rt <- zhen_rt %>%
    mutate(expr_id = factor(expr_id, levels = c("ZH", "EN"), labels=c("ZH", "EN")),
           rev = factor(rev, levels = c("Full", "Upper", "Lower"), labels=c("Full", "Upper", "Lower"))) %>%
  ################# if want to filter out outliers whose rt is 3sd away from the mean #################
  #   group_by(expr_id, rev) %>%
  # group_modify(~ {
  #   df <- .
  #   df %>%
  #     filter(
  #       between(first_duration,
  #               mean(first_duration, na.rm = TRUE) - 3 * sd(first_duration, na.rm = TRUE),
  #               mean(first_duration, na.rm = TRUE) + 3 * sd(first_duration, na.rm = TRUE)),
  #       between(total_duration,
  #               mean(total_duration, na.rm = TRUE) - 3 * sd(total_duration, na.rm = TRUE),
  #               mean(total_duration, na.rm = TRUE) + 3 * sd(total_duration, na.rm = TRUE)),
  #       between(gaze_duration,
  #               mean(gaze_duration, na.rm = TRUE) - 3 * sd(gaze_duration, na.rm = TRUE),
  #               mean(gaze_duration, na.rm = TRUE) + 3 * sd(gaze_duration, na.rm = TRUE)),
  #       between(go_past_time,
  #               mean(go_past_time, na.rm = TRUE) - 3 * sd(go_past_time, na.rm = TRUE),
  #               mean(go_past_time, na.rm = TRUE) + 3 * sd(go_past_time, na.rm = TRUE))
  #     )
  # }) %>%
#############################################################################################
  group_by(expr_id, subj, rev) %>%
  summarise(mean_fd = mean(first_duration, na.rm = TRUE),
            mean_td = mean(total_duration, na.rm = TRUE),
            mean_gd = mean(gaze_duration, na.rm = TRUE),
            mean_gpt = mean(go_past_time, na.rm = TRUE),
            mean_fpfix = mean(FPFix, na.rm = TRUE),
            mean_fpreg = mean(FPReg, na.rm = TRUE),
            mean_regin = mean(RegIn_incl, na.rm = TRUE),
            mean_nfix = mean(NFix, na.rm = TRUE),
            mean_skip = mean(skip, na.rm = TRUE),
            .groups = "drop") %>%
  pivot_wider(names_from = rev, values_from = c(mean_fd, mean_td, mean_gd, mean_gpt, mean_fpfix, mean_fpreg, mean_regin, mean_nfix, mean_skip))

subj_rt
```

```{r t-test by-subj Comparison, echo=FALSE, warning=FALSE, eval=FALSE}
measures <- c("mean_fd", "mean_td", "mean_gd", "mean_gpt",
              "mean_fpfix", "mean_fpreg", "mean_regin", "mean_nfix", "mean_skip")

run_pairwise_t <- function(df, prefix) {
  list(
    upper_vs_whole = t.test(df[[paste0(prefix, "_Upper")]], df[[paste0(prefix, "_Full")]], paired = TRUE),
    upper_vs_lower = t.test(df[[paste0(prefix, "_Upper")]], df[[paste0(prefix, "_Lower")]], paired = TRUE),
    whole_vs_lower = t.test(df[[paste0(prefix, "_Full")]], df[[paste0(prefix, "_Lower")]], paired = TRUE)
  )
}

temp_zh <- subj_rt %>%
  filter(expr_id == "ZH")
temp_en <- subj_rt %>%
  filter(expr_id == "EN")
# Apply the t-tests and extract p-values
t_test_results_zh <- lapply(measures, function(m) run_pairwise_t(temp_zh, m))
t_test_results_en <- lapply(measures, function(m) run_pairwise_t(temp_en, m))
names(t_test_results_zh) <- measures
names(t_test_results_en) <- measures

t_test_results_zh
t_test_results_en
```


```{r Mean RT diff boxplot, echo=TRUE, warning=FALSE, eval=TRUE}
set.seed(123)

subj_gd_long <- subj_rt %>%
  dplyr::select(expr_id, subj, starts_with("mean_gd_")) %>%
  pivot_longer(
    cols = starts_with("mean_gd_"),
    names_to = "rev",
    values_to = "mean_gd"
  ) %>%
  mutate(
    rev = sub("mean_gd_", "", rev),
    rev = factor(rev, levels = c("Full", "Upper", "Lower"))
  )

highlight_subjs <- subj_gd_long %>%
  distinct(expr_id, subj) %>%
  group_by(expr_id) %>%
  slice_sample(n = 5) %>%
  ungroup()
highlight_subjs

subj_gd_long <- subj_gd_long %>%
  mutate(highlight = subj %in% highlight_subjs$subj & expr_id %in% highlight_subjs$expr_id)

ggplot(subj_gd_long, aes(x = rev, y = mean_gd)) +
  geom_boxplot(aes(fill = rev), outlier.shape = NA, alpha = 0.8) +
  # Light gray lines for all subjects (with jitter on x)
  geom_line(data = subj_gd_long, aes(group = subj), size = 0.4, position = position_dodge(0.2), alpha=0.15) +
  # geom_line(data = filter(subj_gd_long, highlight), aes(group = subj, color = subj), position = position_dodge(0.2), linewidth=0.8) +
  geom_point(data = subj_gd_long, aes(group = subj), size = 1, position = position_dodge(0.2), alpha=0.15) +
  # geom_point(data = filter(subj_gd_long, highlight),aes(group = subj, color = subj), size = 2, position = position_dodge(0.2)) +
  scale_fill_brewer(palette = "Set2", name = "Visibility") +
  # facet_wrap(~ expr_id, scales = "free_y", ncol = 1) +
  facet_grid(expr_id~"FPRT" , scales = "free_y") +
  labs(
    title = NULL,
    x = NULL,
    y = "FPRT (ms)"
  ) +
  # coord_cartesian(ylim = c(NA, 750)) + 
  theme_light(base_size = 16) +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "gray85", color = "black", linewidth = 1),
    strip.text = element_text(size = 16, color = "black"),
    legend.title = element_text(size = 16),
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title.y = element_text(size = 18)
  )
# ggsave("./visualization/zh_char_mean_gd_difference_boxplot_vertical.pdf", width = 3.5, height = 6)
```

```{r Density Data, echo=TRUE, warning=FALSE, eval=TRUE}
 measures = c("total_duration")
 languages = c("ZH", "EN")
 rev = c("Whole", "Upper", "Lower")
 predictors = c("len", "freq", "surp", "renyi")
 # predictors = c("surp")

get_d_points = function(df, p) {
  values = df[[p]]
  dens = density(values, na.rm = TRUE)
  data.frame(x = dens$x, y = dens$y)
}

measure_cols <- c("first_duration", "total_duration", "gaze_duration", "go_past_time", 
                  "FPFix", "FPReg", "RegIn_incl", "NFix", "skip")

zhen_long <- zhen_rt %>%
  pivot_longer(
    cols = all_of(measure_cols),
    names_to = "measure",
    values_to = "value"
  )


density_data = data.frame()

for (m in measures){
  for (p in predictors) {
    for(l in languages) {
      dummy_df = zhen_long %>%
        filter(expr_id == l, measure == m) %>%
        do({get_d_points(., p)}) %>%
        filter(x>0, x<20)
      density_data = rbind(density_data, dummy_df %>% mutate(language = l, predictor = p))
      }
  }
}

density_data <- density_data %>%
    mutate(predictor = factor(predictor, levels = c("len", "freq", "surp", "renyi"), labels = c("Word Length", "Zipf Frequency", "Surprisal", "Entropy")),
         language = factor(language, levels = c("ZH-CN", "EN")))

# write.csv(density_data, "./precomputed/density.csv")
```

```{r}
density_data <- read.csv("./precomputed/density.csv")

ggplot(density_data, aes(x = x, y = y)) +
  geom_line(size = 0.8) +
  scale_x_continuous(breaks = c(0, 10, 20), labels = c(0, 10, 20), minor_breaks = NULL) +
  facet_grid(language ~ predictor) +
  ylab("Density") +
  xlab("Predictor Value") +
  ggtitle("Density plots for Predictors across Languages") +
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank()
  )
```


